esphome:
  name: esp32_bedroom
  friendly_name: esp32_bedroom
  #  compile_process_limit: 1

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "eKTR9qFwvUK7t8daAdWhshvzi+LAvY2GfPYeu0sdz1E="

ota:
  - platform: esphome
    password: "a7b796a9f5fdf57d86d46561cd31e2da"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.178.249
    gateway: 192.168.178.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Test Fallback Hotspot"
    password: "enNvCrVeN3li"

captive_portal:

# http
web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

  - platform: uptime
    type: seconds
    name: Uptime Sensor

  - platform: internal_temperature
    name: "Internal Temperature"

  - platform: dht
    pin: GPIO26
    model: DHT22
    temperature:
      name: "Bedroom Temperature"
    humidity:
      name: "Bedroom Humidity"
    update_interval: 60s
